/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import controller.*;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.util.List;
import model.*;

/**
 *
 * @author Johnthor
 */
public class UISistemInformasiMahasiswa extends javax.swing.JFrame {
    private MahasiswaController mahasiswaController = new MahasiswaController();
    private MataKuliahController mataKuliahController = new MataKuliahController();
    private NilaiController nilaiController = new NilaiController();
    private int selectedIdNilai = 0;

  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UISistemInformasiMahasiswa.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public UISistemInformasiMahasiswa () {
        initComponents();
        loadMahasiswaData();
        loadMatkulData();
        loadNilaiData();
        loadComboMahasiswa();
        loadComboMatkul();
        setLocationRelativeTo(null);
        jTableMahasiswa.setDefaultEditor(Object.class, null);
        jTableMatkul.setDefaultEditor(Object.class, null);
        jTableNilai.setDefaultEditor(Object.class, null);
        jTableNilai.getColumnModel().getColumn(0).setMinWidth(0);
        jTableNilai.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableNilai.getColumnModel().getColumn(0).setWidth(0);
        jTableNilai.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTextFieldNilaiHuruf.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldNilaiHuruf.setEditable(false);
       

    }
private void loadMahasiswaData() {
    DefaultTableModel model = (DefaultTableModel) jTableMahasiswa.getModel();
    model.setRowCount(0);

    mahasiswaController.getAll().forEach(m -> {
        model.addRow(new Object[]{
            m.getNim(),
            m.getNama(),
            m.getJurusan(),
            m.getJenisKelamin(),
            m.getAlamat()
        });
    });
}
private void loadMatkulData() {
    DefaultTableModel model = (DefaultTableModel) jTableMatkul.getModel();
    model.setRowCount(0);

    mataKuliahController.getAll().forEach(mk -> {
        model.addRow(new Object[]{
            mk.getKodeMk(),
            mk.getNamaMk(),
            mk.getSks()
        });
    });
}
private void loadNilaiData() {
    DefaultTableModel model = (DefaultTableModel) jTableNilai.getModel();
    model.setRowCount(0);

    int no = 1;
    for (Nilai n : nilaiController.getAll()) {
        model.addRow(new Object[]{
            n.getIdNilai(),      
            no++,                
            n.getNim(),          
            n.getNamaMahasiswa(),
            n.getKodeMk(),       
            n.getNamaMatkul(),   
            n.getNilai(),        
            n.getNilaiHuruf()    
        });
    }

   
    jTableNilai.getColumnModel().getColumn(0).setMinWidth(0);
    jTableNilai.getColumnModel().getColumn(0).setMaxWidth(0);
    jTableNilai.getColumnModel().getColumn(0).setWidth(0);
    jTableNilai.getColumnModel().getColumn(0).setPreferredWidth(0);
}
    
private void loadComboMahasiswa() {
    jComboBoxNamadiNilai.removeAllItems();

    mahasiswaController.getAll().forEach(m -> {
        jComboBoxNamadiNilai.addItem(m.getNim() + " - " + m.getNama());
    });
}
private void loadComboMatkul() {
    jComboBoxMatkul.removeAllItems();

    mataKuliahController.getAll().forEach(mk -> {
        jComboBoxMatkul.addItem (mk.getKodeMk()+ " - " + mk.getNamaMk());
    });
}
private void clearMahasiswaForm() {
    jTextFieldNIM.setText("");
    jTextFieldNama.setText("");
    jTextFieldAlamat.setText("");
    jComboBoxJurusan.setSelectedIndex(0);
    jComboBoxJenisKelamin.setSelectedIndex(0);
    jTextFieldNIM.setEditable(true);
}

private void clearMatkulForm() {
    jTextFieldKodeMatkul.setText("");
    jTextFieldNamaMatkul.setText("");
    jTextFieldSKS.setText("");
    jTextFieldKodeMatkul.setEditable(true);
}
private void clearNilaiForm() {
    if (jComboBoxNamadiNilai.getItemCount() > 0) jComboBoxNamadiNilai.setSelectedIndex(0);
    if (jComboBoxMatkul.getItemCount() > 0) jComboBoxMatkul.setSelectedIndex(0);
    jTextFieldNilai.setText("");
    jTextFieldNilaiHuruf.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDataMahasiswa = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNIM = new javax.swing.JTextField();
        jComboBoxJurusan = new javax.swing.JComboBox<>();
        jComboBoxJenisKelamin = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jButtonTambahMahasiswa = new javax.swing.JButton();
        jButtonHapusMahasiswa = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonClearMahasiswa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMahasiswa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanelDataMatkul = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMatkul = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldKodeMatkul = new javax.swing.JTextField();
        jButtonTambahMatkul = new javax.swing.JButton();
        jButtonHapusMatkul = new javax.swing.JButton();
        jButtonEditMatkul = new javax.swing.JButton();
        jButtonClearMatkul = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldSKS = new javax.swing.JTextField();
        jTextFieldNamaMatkul = new javax.swing.JTextField();
        jPanelDataNilai = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jComboBoxMatkul = new javax.swing.JComboBox<>();
        jTextFieldNilai = new javax.swing.JTextField();
        jButtonTambahNilaiMahasiswa = new javax.swing.JButton();
        jButtonHapusNilaiMahasiswa = new javax.swing.JButton();
        jButtonEditNilaiMahasiswa = new javax.swing.JButton();
        jButtonClearNilaiMahasiswa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxNamadiNilai = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNilaiHuruf = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNilai = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(41, 128, 185));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI MAHASISWA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manajemen Data Mahasiswa, Mata Kuliah & Nilai");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, -1, -1));

        jButtonLogout.setBackground(new java.awt.Color(204, 204, 204));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jTabbedPane1.setBackground(java.awt.Color.white);

        jPanel5.setBackground(java.awt.Color.white);

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jTextFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIMActionPerformed(evt);
            }
        });

        jComboBoxJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tekink Informatika", "Teknik Mesin", "Tekink Industri", "Ilmu Hukum", "Farmasi", "Keperawatan", "Kedokteran", "Pendididkan Agama Islam", "Pendidikan Guru Sekolah Dasar", "Psikologi" }));
        jComboBoxJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJurusanActionPerformed(evt);
            }
        });

        jComboBoxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perempuan", "Laki - laki" }));
        jComboBoxJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJenisKelaminActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NIM");

        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });

        jButtonTambahMahasiswa.setBackground(new java.awt.Color(39, 174, 96));
        jButtonTambahMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTambahMahasiswa.setForeground(java.awt.Color.white);
        jButtonTambahMahasiswa.setText("Tambah");
        jButtonTambahMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahMahasiswaActionPerformed(evt);
            }
        });

        jButtonHapusMahasiswa.setBackground(new java.awt.Color(231, 76, 60));
        jButtonHapusMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHapusMahasiswa.setForeground(java.awt.Color.white);
        jButtonHapusMahasiswa.setText("Hapus");
        jButtonHapusMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusMahasiswaActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(241, 196, 15));
        jButtonEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEdit.setForeground(java.awt.Color.white);
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonClearMahasiswa.setBackground(new java.awt.Color(236, 240, 241));
        jButtonClearMahasiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonClearMahasiswa.setText("Clear");
        jButtonClearMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearMahasiswaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 152, 219));
        jLabel5.setText("Form Input Data Mahasiswa");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nama Lengkap");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Jurusan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Alamat");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNIM))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNama)
                                .addComponent(jComboBoxJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jButtonTambahMahasiswa)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonHapusMahasiswa)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEdit)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonClearMahasiswa))
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambahMahasiswa)
                    .addComponent(jButtonHapusMahasiswa)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonClearMahasiswa))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel7.setBackground(java.awt.Color.white);

        jTableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jurusan", "Jenis Kelamin", "Alamat"
            }
        ));
        jTableMahasiswa.getTableHeader().setResizingAllowed(false);
        jTableMahasiswa.getTableHeader().setReorderingAllowed(false);
        jTableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMahasiswaMouseClicked(evt);
            }
        });
        jTableMahasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableMahasiswaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMahasiswa);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 152, 219));
        jLabel4.setText("Daftar Mahasiswa");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDataMahasiswaLayout = new javax.swing.GroupLayout(jPanelDataMahasiswa);
        jPanelDataMahasiswa.setLayout(jPanelDataMahasiswaLayout);
        jPanelDataMahasiswaLayout.setHorizontalGroup(
            jPanelDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDataMahasiswaLayout.setVerticalGroup(
            jPanelDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Mahasiswa", jPanelDataMahasiswa);

        jPanel11.setBackground(java.awt.Color.white);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(52, 152, 219));
        jLabel21.setText("Daftar Mata Kuliah");

        jTableMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Matkul", "Matkul", "Jumlah SKS"
            }
        ));
        jTableMatkul.getTableHeader().setResizingAllowed(false);
        jTableMatkul.getTableHeader().setReorderingAllowed(false);
        jTableMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMatkulMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableMatkul);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 590, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );

        jPanel10.setBackground(java.awt.Color.white);

        jTextFieldKodeMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeMatkulActionPerformed(evt);
            }
        });

        jButtonTambahMatkul.setBackground(new java.awt.Color(39, 174, 96));
        jButtonTambahMatkul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTambahMatkul.setForeground(java.awt.Color.white);
        jButtonTambahMatkul.setText("Tambah");
        jButtonTambahMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahMatkulActionPerformed(evt);
            }
        });

        jButtonHapusMatkul.setBackground(new java.awt.Color(231, 76, 60));
        jButtonHapusMatkul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHapusMatkul.setForeground(java.awt.Color.white);
        jButtonHapusMatkul.setText("Hapus");
        jButtonHapusMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusMatkulActionPerformed(evt);
            }
        });

        jButtonEditMatkul.setBackground(new java.awt.Color(241, 196, 15));
        jButtonEditMatkul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEditMatkul.setForeground(java.awt.Color.white);
        jButtonEditMatkul.setText("Edit");
        jButtonEditMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditMatkulActionPerformed(evt);
            }
        });

        jButtonClearMatkul.setBackground(new java.awt.Color(236, 240, 241));
        jButtonClearMatkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonClearMatkul.setText("Clear");
        jButtonClearMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearMatkulActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(52, 152, 219));
        jLabel13.setText("Form Input Mata Kuliah");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Kode Matkul");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Mata Kuliah");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Jumlah SKS");

        jTextFieldSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSKSActionPerformed(evt);
            }
        });

        jTextFieldNamaMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaMatkulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel18))
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaMatkul, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jTextFieldKodeMatkul)))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jButtonTambahMatkul)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonHapusMatkul)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEditMatkul)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonClearMatkul))))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldKodeMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambahMatkul)
                    .addComponent(jButtonHapusMatkul)
                    .addComponent(jButtonEditMatkul)
                    .addComponent(jButtonClearMatkul))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDataMatkulLayout = new javax.swing.GroupLayout(jPanelDataMatkul);
        jPanelDataMatkul.setLayout(jPanelDataMatkulLayout);
        jPanelDataMatkulLayout.setHorizontalGroup(
            jPanelDataMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataMatkulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDataMatkulLayout.setVerticalGroup(
            jPanelDataMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataMatkulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Data Mata Kuliah", jPanelDataMatkul);

        jPanel8.setBackground(java.awt.Color.white);

        jComboBoxMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMatkulActionPerformed(evt);
            }
        });

        jTextFieldNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNilaiActionPerformed(evt);
            }
        });
        jTextFieldNilai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNilaiKeyReleased(evt);
            }
        });

        jButtonTambahNilaiMahasiswa.setBackground(new java.awt.Color(39, 174, 96));
        jButtonTambahNilaiMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTambahNilaiMahasiswa.setForeground(java.awt.Color.white);
        jButtonTambahNilaiMahasiswa.setText("Tambah");
        jButtonTambahNilaiMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahNilaiMahasiswaActionPerformed(evt);
            }
        });

        jButtonHapusNilaiMahasiswa.setBackground(new java.awt.Color(231, 76, 60));
        jButtonHapusNilaiMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHapusNilaiMahasiswa.setForeground(java.awt.Color.white);
        jButtonHapusNilaiMahasiswa.setText("Hapus");
        jButtonHapusNilaiMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusNilaiMahasiswaActionPerformed(evt);
            }
        });

        jButtonEditNilaiMahasiswa.setBackground(new java.awt.Color(241, 196, 15));
        jButtonEditNilaiMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEditNilaiMahasiswa.setForeground(java.awt.Color.white);
        jButtonEditNilaiMahasiswa.setText("Edit");
        jButtonEditNilaiMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditNilaiMahasiswaActionPerformed(evt);
            }
        });

        jButtonClearNilaiMahasiswa.setBackground(new java.awt.Color(236, 240, 241));
        jButtonClearNilaiMahasiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonClearNilaiMahasiswa.setText("Clear");
        jButtonClearNilaiMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearNilaiMahasiswaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(52, 152, 219));
        jLabel11.setText("Form Input Nilai Mahasiswa");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("NIM dan Nama");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Mata Kuliah");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Nilai");

        jComboBoxNamadiNilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNamadiNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNamadiNilaiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Nilai Huruf");

        jTextFieldNilaiHuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNilaiHurufActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonTambahNilaiMahasiswa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapusNilaiMahasiswa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditNilaiMahasiswa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClearNilaiMahasiswa))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jLabel14))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxMatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNilai)
                                    .addComponent(jTextFieldNilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxNamadiNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxNamadiNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldNilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambahNilaiMahasiswa)
                    .addComponent(jButtonHapusNilaiMahasiswa)
                    .addComponent(jButtonEditNilaiMahasiswa)
                    .addComponent(jButtonClearNilaiMahasiswa))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel9.setBackground(java.awt.Color.white);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "No", "NIM", "Nama Mahasiswa", "Kode Matkul", "Matkul", "Nilai", "Nilai Huruf"
            }
        ));
        jTableNilai.getTableHeader().setResizingAllowed(false);
        jTableNilai.getTableHeader().setReorderingAllowed(false);
        jTableNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNilaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNilai);
        if (jTableNilai.getColumnModel().getColumnCount() > 0) {
            jTableNilai.getColumnModel().getColumn(0).setResizable(false);
            jTableNilai.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(52, 152, 219));
        jLabel16.setText("Transkip Nilai Mahasiswa");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDataNilaiLayout = new javax.swing.GroupLayout(jPanelDataNilai);
        jPanelDataNilai.setLayout(jPanelDataNilaiLayout);
        jPanelDataNilaiLayout.setHorizontalGroup(
            jPanelDataNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDataNilaiLayout.setVerticalGroup(
            jPanelDataNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Nilai", jPanelDataNilai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin keluar?", 
            "Konfirmasi Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    // 2. Jika user memilih YES
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        // Buka kembali halaman Login (NewJFrame)
        LoginPage lp = new LoginPage();
        
        // Pastikan halaman login muncul di tengah layar (Konsisten)
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
        
        // Tutup halaman Admin saat ini
        this.dispose();
    }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTableNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNilaiMouseClicked
        int row = jTableNilai.getSelectedRow();

        if (row >= 0) {
            // Ambil ID dari kolom 0 (yang di-hidden tadi)
            selectedIdNilai = Integer.parseInt(jTableNilai.getValueAt(row, 0).toString());

            // NIM & Nama (Index 2 & 3)
            String nimNama = jTableNilai.getValueAt(row, 2).toString() + " - " + jTableNilai.getValueAt(row, 3).toString();
            jComboBoxNamadiNilai.setSelectedItem(nimNama);

            // Kode & Matkul (Index 4 & 5)
            String kodeMatkul = jTableNilai.getValueAt(row, 4).toString() + " - " + jTableNilai.getValueAt(row, 5).toString();
            jComboBoxMatkul.setSelectedItem(kodeMatkul);

            // Nilai (Index 6)
            jTextFieldNilai.setText(jTableNilai.getValueAt(row, 6).toString());

            // Nilai Huruf (Index 7)
            jTextFieldNilaiHuruf.setText(jTableNilai.getValueAt(row, 7).toString());
        }
    }//GEN-LAST:event_jTableNilaiMouseClicked

    private void jTextFieldNilaiHurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiHurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiHurufActionPerformed

    private void jComboBoxNamadiNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNamadiNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNamadiNilaiActionPerformed

    private void jButtonClearNilaiMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearNilaiMahasiswaActionPerformed
        clearNilaiForm();
    }//GEN-LAST:event_jButtonClearNilaiMahasiswaActionPerformed

    private void jButtonEditNilaiMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditNilaiMahasiswaActionPerformed
        try {
            int row = jTableNilai.getSelectedRow();
            if (selectedIdNilai <= 0) {
                JOptionPane.showMessageDialog(this, "Klik data nilai di tabel dulu");
                return;
            }
            String nim = jComboBoxNamadiNilai.getSelectedItem() == null ? "" : jComboBoxNamadiNilai.getSelectedItem().toString().trim();
            String kodeMk = jComboBoxMatkul.getSelectedItem() == null ? "" : jComboBoxMatkul.getSelectedItem().toString().trim();
            int nilai = Integer.parseInt(jTextFieldNilai.getText().trim());

            nilaiController.update(selectedIdNilai, nim, kodeMk, nilai);

            JOptionPane.showMessageDialog(this, "Nilai berhasil diupdate");
            loadNilaiData();
            clearNilaiForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nilai harus angka 0-100");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditNilaiMahasiswaActionPerformed

    private void jButtonHapusNilaiMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusNilaiMahasiswaActionPerformed
        try {
            int row = jTableNilai.getSelectedRow();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu");
                return;
            }

            int idNilai = Integer.parseInt(
                jTableNilai.getValueAt(row, 1).toString() // kolom id_nilai
            );

            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin hapus data nilai ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                nilaiController.hapus(idNilai);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                loadNilaiData();
                clearNilaiForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonHapusNilaiMahasiswaActionPerformed

    private void jButtonTambahNilaiMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahNilaiMahasiswaActionPerformed
        try {
            String selectednim = jComboBoxNamadiNilai.getSelectedItem().toString().trim();
            String nim = selectednim.split(" - ")[0];

            String selectedMk = jComboBoxMatkul.getSelectedItem().toString();
            String kodeMk = selectedMk.split(" - ")[0]; // FIX PENTING

            int nilai = Integer.parseInt(jTextFieldNilai.getText().trim());

            nilaiController.simpan(nim, kodeMk, nilai);

            JOptionPane.showMessageDialog(this, "Nilai berhasil ditambahkan");
            loadNilaiData();
            clearNilaiForm();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nilai harus berupa angka 0 - 100");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonTambahNilaiMahasiswaActionPerformed

    private void jTextFieldNilaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNilaiKeyReleased
        try {
            String input = jTextFieldNilai.getText().trim();
            if (input.isEmpty()) {
                jTextFieldNilaiHuruf.setText("");
                return;
            }

            int nilaiAngka = Integer.parseInt(input);

            // Panggil method controller yang sudah diubah jadi public
            String huruf = nilaiController.hitungNilaiHuruf(nilaiAngka);

            jTextFieldNilaiHuruf.setText(huruf);
        } catch (NumberFormatException e) {
            jTextFieldNilaiHuruf.setText("");
        }
    }//GEN-LAST:event_jTextFieldNilaiKeyReleased

    private void jTextFieldNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiActionPerformed

    private void jComboBoxMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMatkulActionPerformed

    private void jTextFieldNamaMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaMatkulActionPerformed

    private void jTextFieldSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSKSActionPerformed

    private void jButtonClearMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearMatkulActionPerformed
        clearMatkulForm();
    }//GEN-LAST:event_jButtonClearMatkulActionPerformed

    private void jButtonEditMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMatkulActionPerformed
        try{

            int row = jTableMatkul.getSelectedRow();

            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Pilih data di tabel");
                return;
            }

            jTextFieldKodeMatkul.setEditable(true);

            String kode = jTextFieldKodeMatkul.getText().trim();
            String nama = jTextFieldNamaMatkul.getText().trim();
            int sks = Integer.parseInt(jTextFieldSKS.getText().trim());

            mataKuliahController.update(kode, nama, sks);
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

            loadMatkulData();
            clearMatkulForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditMatkulActionPerformed

    private void jButtonHapusMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusMatkulActionPerformed
        int row = jTableMatkul.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel");
            return;
        }

        String kode = jTableMatkul.getValueAt(row, 0).toString();

        if (JOptionPane.showConfirmDialog(
            this, "Hapus mata kuliah " + kode + "?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION
        ) == JOptionPane.YES_OPTION) {

            mataKuliahController.hapus(kode);
            loadMatkulData();
            clearMatkulForm();
        }
    }//GEN-LAST:event_jButtonHapusMatkulActionPerformed

    private void jButtonTambahMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahMatkulActionPerformed
        try {
            String kode = jTextFieldKodeMatkul.getText().trim();
            String nama = jTextFieldNamaMatkul.getText().trim();
            String sksStr = jTextFieldSKS.getText().trim();

            if (kode.isEmpty() || nama.isEmpty() || sksStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field wajib diisi");
                return;
            }

            int sks = Integer.parseInt(sksStr);
            mataKuliahController.simpan(kode, nama, sks);

            JOptionPane.showMessageDialog(this, "Data mata kuliah berhasil ditambahkan");
            loadMatkulData();
            loadComboMatkul();
            clearMatkulForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "SKS harus berupa angka");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonTambahMatkulActionPerformed

    private void jTextFieldKodeMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeMatkulActionPerformed

    private void jTableMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMatkulMouseClicked

        int row = jTableMatkul.getSelectedRow();
        jTextFieldKodeMatkul.setText(jTableMatkul.getValueAt(row,0).toString());
        jTextFieldNamaMatkul.setText(jTableMatkul.getValueAt(row,1).toString());
        jTextFieldSKS.setText(jTableMatkul.getValueAt(row,2).toString());
    }//GEN-LAST:event_jTableMatkulMouseClicked

    private void jTableMahasiswaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableMahasiswaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMahasiswaKeyPressed

    private void jTableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMahasiswaMouseClicked
        int row = jTableMahasiswa.getSelectedRow();
        if (row >= 0) {
            jTextFieldNIM.setText(jTableMahasiswa.getValueAt(row, 0).toString());
            jTextFieldNama.setText(jTableMahasiswa.getValueAt(row, 1).toString());
            jComboBoxJurusan.setSelectedItem(jTableMahasiswa.getValueAt(row, 2).toString());
            jComboBoxJenisKelamin.setSelectedItem(jTableMahasiswa.getValueAt(row, 3).toString());
            jTextFieldAlamat.setText(jTableMahasiswa.getValueAt(row, 4).toString());

            // kunci NIM saat edit
            jTextFieldNIM.setEditable(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMahasiswaMouseClicked

    private void jButtonClearMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearMahasiswaActionPerformed
        clearMahasiswaForm();
    }//GEN-LAST:event_jButtonClearMahasiswaActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        try {
            String nim = jTextFieldNIM.getText().trim();
            String nama = jTextFieldNama.getText().trim();
            String jurusan = jComboBoxJurusan.getSelectedItem().toString();
            String jk = jComboBoxJenisKelamin.getSelectedItem().toString();
            String alamat = jTextFieldAlamat.getText().trim();

            mahasiswaController.update(nim, nama, jurusan, jk, alamat);

            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diupdate");
            loadMahasiswaData();
            clearMahasiswaForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusMahasiswaActionPerformed
        int row = jTableMahasiswa.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu");
            return;
        }

        String nim = jTableMahasiswa.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin hapus mahasiswa dengan NIM " + nim + "?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            mahasiswaController.hapus(nim);

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            loadMahasiswaData();
            clearMahasiswaForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Terjadi Kesalahan",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonHapusMahasiswaActionPerformed

    private void jButtonTambahMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahMahasiswaActionPerformed
        try {
            String nim = jTextFieldNIM.getText().trim();
            String nama = jTextFieldNama.getText().trim();
            String jurusan = jComboBoxJurusan.getSelectedItem().toString();
            String jk = jComboBoxJenisKelamin.getSelectedItem().toString();
            String alamat = jTextFieldAlamat.getText().trim();

            mahasiswaController.simpan(nim, nama, jurusan, jk, alamat);

            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil ditambahkan");
            loadMahasiswaData();
            loadComboMahasiswa();
            clearMahasiswaForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTambahMahasiswaActionPerformed

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jComboBoxJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJenisKelaminActionPerformed

    private void jComboBoxJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJurusanActionPerformed

    private void jTextFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIMActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed


    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new UISistemInformasiMahasiswa().setVisible(true));
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonClearMahasiswa;
    private javax.swing.JButton jButtonClearMatkul;
    private javax.swing.JButton jButtonClearNilaiMahasiswa;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEditMatkul;
    private javax.swing.JButton jButtonEditNilaiMahasiswa;
    private javax.swing.JButton jButtonHapusMahasiswa;
    private javax.swing.JButton jButtonHapusMatkul;
    private javax.swing.JButton jButtonHapusNilaiMahasiswa;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTambahMahasiswa;
    private javax.swing.JButton jButtonTambahMatkul;
    private javax.swing.JButton jButtonTambahNilaiMahasiswa;
    private javax.swing.JComboBox<String> jComboBoxJenisKelamin;
    private javax.swing.JComboBox<String> jComboBoxJurusan;
    private javax.swing.JComboBox<String> jComboBoxMatkul;
    private javax.swing.JComboBox<String> jComboBoxNamadiNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDataMahasiswa;
    private javax.swing.JPanel jPanelDataMatkul;
    private javax.swing.JPanel jPanelDataNilai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMahasiswa;
    private javax.swing.JTable jTableMatkul;
    private javax.swing.JTable jTableNilai;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldKodeMatkul;
    private javax.swing.JTextField jTextFieldNIM;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNamaMatkul;
    private javax.swing.JTextField jTextFieldNilai;
    private javax.swing.JTextField jTextFieldNilaiHuruf;
    private javax.swing.JTextField jTextFieldSKS;
    // End of variables declaration//GEN-END:variables
}
